# Generated by Django 5.2.16 on 2026-08-02 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_availabilityperiod_availabilityrange_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilityrange',
            name='period',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='provider',
        ),
        migrations.DeleteModel(
            name='AvailabilityPeriod',
        ),
        migrations.DeleteModel(
            name='AvailabilityRange',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
