# Generated by Django 5.2.16 on 2026-08-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_availabilityrange_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='address',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
