# Generated by Django 5.2.16 on 2026-08-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_providerprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='employer',
            field=models.CharField(default='self-employed', max_length=50),
        ),
    ]
