# Generated by Django 5.2.16 on 2026-08-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_providerprofile_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
