# Generated by Django 5.2.16 on 2026-08-02 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_remove_availabilityrange_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_from', models.DateField()),
                ('active_until', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='appointments.availabilityperiod')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_type', models.CharField(choices=[('general_practitioner', 'General Practitioner / Family Physician'), ('internal_medicine', 'Internist (Internal Medicine)'), ('pediatrician', 'Pediatrician (Child Specialist)'), ('geriatrician', 'Geriatrician (Elderly Care)'), ('general_surgeon', 'General Surgeon'), ('orthopedic_surgeon', 'Orthopedic Surgeon (Bones & Joints)'), ('neurosurgeon', 'Neurosurgeon (Brain & Spine)'), ('cardiothoracic_surgeon', 'Cardiothoracic Surgeon (Heart & Chest)'), ('plastic_surgeon', 'Plastic & Reconstructive Surgeon'), ('cardiologist', 'Cardiologist (Heart Specialist)'), ('dermatologist', 'Dermatologist (Skin, Hair & Nails)'), ('endocrinologist', 'Endocrinologist (Hormones & Diabetes)'), ('gastroenterologist', 'Gastroenterologist (Digestive System)'), ('hematologist', 'Hematologist (Blood Disorders)'), ('nephrologist', 'Nephrologist (Kidney Specialist)'), ('neurologist', 'Neurologist (Brain & Nervous System)'), ('oncologist', 'Oncologist (Cancer Specialist)'), ('pulmonologist', 'Pulmonologist (Lungs & Respiratory)'), ('rheumatologist', 'Rheumatologist (Autoimmune & Joints)'), ('gynecologist', 'Gynecologist'), ('obstetrician', 'Obstetrician (Pregnancy & Childbirth)'), ('urologist', 'Urologist (Urinary & Male Reproductive)'), ('psychiatrist', 'Psychiatrist (Mental Health)'), ('ophthalmologist', 'Ophthalmologist (Eye Specialist)'), ('ent_specialist', 'ENT Specialist (Otolaryngologist)'), ('dentist', 'Dentist / Oral Surgeon'), ('allergist', 'Allergist / Immunologist'), ('anesthesiologist', 'Anesthesiologist'), ('radiologist', 'Radiologist (Imaging)'), ('pathologist', 'Pathologist (Lab Diagnostics)'), ('emergency_physician', 'Emergency Medicine Specialist'), ('physiatrist', 'Physiatrist (Physical Medicine & Rehab)')], max_length=50)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('fee_enabled', models.BooleanField(default=False)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='accounts.providerprofile')),
            ],
        ),
        migrations.AddField(
            model_name='availabilityperiod',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_periods', to='appointments.doctor'),
        ),
    ]
