# Generated by Django 5.2.16 on 2026-08-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_customavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='chapa_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='tx_ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
