# Generated by Django 5.2.16 on 2026-07-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_item_orderitem_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='dosage',
            new_name='dosages',
        ),
    ]
